apiVersion: v1
kind: PersistentVolume
metadata:
  name: entries-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/entries

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: entries-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
