apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-service
spec:
  selector:
    app: {{ .Values.auth.label }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.auth.servicePort }}
      targetPort: {{ .Values.auth.targetPort }}