apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.users.name }}-service
spec:
  selector:
    app: {{ .Values.users.label }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.users.servicePort }}
      targetPort: {{ .Values.users.targetPort }}
